# vim:fileencoding=utf-8:foldmethod=marker

kitty_mod ctrl+shift 

# BEGIN_KITTY_FONTS
font_family      family="JetBrains Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# font_features FiraCode-Regular +cv02 +ss03
# font_features FiraCode-Bold    +cv02 +ss03
# font_features FiraCode-SemiBold    +cv02 +ss03
# font_features FiraCode-Medium  +cv02 +ss03
# font_features FiraCode-Retina  +cv02 +ss03
# font_features FiraCode-Light  +cv02 +ss03
font_size 11.0

map kitty_mod+minus change_font_size all -1.0
map kitty_mod+kp_subtract change_font_size all -1.0

map kitty_mod+equal change_font_size all +1.0
map kitty_mod+plus change_font_size all +1.0
map kitty_mod+kp_add change_font_size all +1.0

disable_ligatures never
# text_composition_strategy legacy

modify_font cell_height +2px

# cursor customization
## block / beam / underline
cursor_shape block 
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration no-cursor

# cursor_trail 9
# cursor_trail_start_threshold 3
# cursor_trail_decay    0.06  0.18 

# cursor_trail 1
# cursor_trail_start_threshold 1
# cursor_trail_decay 0.03 0.06

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
# wayland_titlebar_color system
hide_window_decorations yes

tab_bar_style powerline
tab_powerline_style round
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal


tab_title_template "{index} {'' if layout_name == 'stack' else ''} {title}"

# --- Layouts Allowed ---
enabled_layouts splits,stack,tall,grid

# --- Tab Management (The "Shift" Layer) ---
map kitty_mod+t new_tab_with_cwd
map kitty_mod+l next_tab
map kitty_mod+h previous_tab
map kitty_mod+q close_tab

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab -1

# --- Window Management (The "Direct" Layer) ---
map kitty_mod+enter new_window_with_cwd
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# --- Layout Switching & Stack Logic ---
map kitty_mod+k next_layout

# Quick toggle for "Zoom" (Stack)
map kitty_mod+z toggle_layout stack

# move tab
map kitty_mod+. move_tab_forward 
map kitty_mod+, move_tab_backward 


# --- Direct Layout Jumps (Alt Layer) ---
map alt+shift+t goto_layout tall
map alt+shift+g goto_layout grid
map alt+shift+s goto_layout splits

# --- Manual Splitting (For 'splits' layout) ---
map ctrl+alt+v launch --location=vsplit --cwd=current
map ctrl+alt+h launch --location=hsplit --cwd=current

window_padding_width 6
copy_on_select yes

# background_image path/image.png
# background_image_layout scaled
# background_tint 0.8

shell fish
